[project]
name = "mcp-server-dota2-tip"
version = "0.1.0"
description = "A MCP Server to get data over a hero using Opendota API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.4",
    "requests>=2.32.4",
]
